OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "sk-gbUMG4zkITB7sJ7SB0Bf6eFe4bE345418217FaAbCaD38324"
  base_url: "https://api.xiaoai.plus/v1"

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"